-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
-- Version: 2020.2.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity colordetect_accel_xfdilate_2160_3840_1_0_1_0_3841_3_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgHelper2_4102_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    imgHelper2_4102_empty_n : IN STD_LOGIC;
    imgHelper2_4102_read : OUT STD_LOGIC;
    imgHelper3_4103_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgHelper3_4103_full_n : IN STD_LOGIC;
    imgHelper3_4103_write : OUT STD_LOGIC;
    img_height : IN STD_LOGIC_VECTOR (15 downto 0);
    img_width : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of colordetect_accel_xfdilate_2160_3840_1_0_1_0_3841_3_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_pp3_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal imgHelper2_4102_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln878_reg_873 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp3_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp3_stage0 : signal is "none";
    signal ap_enable_reg_pp3_iter1 : STD_LOGIC := '0';
    signal ap_block_pp3_stage0 : BOOLEAN;
    signal icmp_ln878_17_reg_926 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_18_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i115_i_reg_903 : STD_LOGIC_VECTOR (0 downto 0);
    signal imgHelper3_4103_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp3_iter5 : STD_LOGIC := '0';
    signal icmp_ln882_reg_954 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln882_reg_954_pp3_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_col_046_0_reg_262 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_reg_330 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_reg_330_pp3_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state10_pp3_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op126_read_state11 : BOOLEAN;
    signal ap_block_state11_pp3_stage0_iter1 : BOOLEAN;
    signal ap_block_state12_pp3_stage0_iter2 : BOOLEAN;
    signal ap_block_state13_pp3_stage0_iter3 : BOOLEAN;
    signal ap_block_state14_pp3_stage0_iter4 : BOOLEAN;
    signal ap_block_state15_pp3_stage0_iter5 : BOOLEAN;
    signal ap_block_pp3_stage0_11001 : BOOLEAN;
    signal src_buf_V_0_0_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_4_reg_389 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_1_0_reg_400 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_3_reg_412 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_2_0_reg_424 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_478_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_reg_840 : STD_LOGIC_VECTOR (13 downto 0);
    signal init_row_ind_fu_482_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal row_ind_V_0_0_load_reg_850 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_1_0_load_reg_855 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_2_0_load_reg_860 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln691_fu_522_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln691_reg_868 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal ap_block_state4_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal icmp_ln878_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln691_4_fu_542_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal op2_assign_fu_565_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal op2_assign_reg_885 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln1616_fu_571_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln1616_reg_890 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln878_15_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_15_reg_895 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_16_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal cmp_i_i115_i_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln123_fu_610_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln123_reg_907 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln136_fu_614_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln136_reg_911 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln136_1_fu_618_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln136_1_reg_916 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_V_2_fu_622_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_2_reg_921 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_enable_reg_pp3_iter0 : STD_LOGIC := '0';
    signal icmp_ln878_17_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_17_reg_926_pp3_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_17_reg_926_pp3_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_17_reg_926_pp3_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_17_reg_926_pp3_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_18_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_18_reg_930_pp3_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_18_reg_930_pp3_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln882_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln882_reg_954_pp3_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_685_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_0_1_reg_963 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp3_iter3 : STD_LOGIC := '0';
    signal max_V_11_fu_716_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_11_reg_968 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_1_1_reg_974 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp3_iter4 : STD_LOGIC := '0';
    signal src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_2_1_reg_979 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_15_fu_770_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_V_15_reg_986 : STD_LOGIC_VECTOR (7 downto 0);
    signal row_V_2_fu_803_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state4 : STD_LOGIC;
    signal ap_block_pp3_stage0_subdone : BOOLEAN;
    signal ap_condition_pp3_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp3_iter2 : STD_LOGIC := '0';
    signal ap_condition_pp3_exit_iter4_state14 : STD_LOGIC;
    signal buf_V_0_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_0_ce0 : STD_LOGIC;
    signal buf_V_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_0_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_0_ce1 : STD_LOGIC;
    signal buf_V_0_we1 : STD_LOGIC;
    signal buf_V_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_1_ce0 : STD_LOGIC;
    signal buf_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_1_ce1 : STD_LOGIC;
    signal buf_V_1_we1 : STD_LOGIC;
    signal buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_2_ce0 : STD_LOGIC;
    signal buf_V_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_V_2_ce1 : STD_LOGIC;
    signal buf_V_2_we1 : STD_LOGIC;
    signal buf_V_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_ready : STD_LOGIC;
    signal src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_ready : STD_LOGIC;
    signal src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472_ap_ready : STD_LOGIC;
    signal ap_phi_mux_row_ind_V_1_phi_fu_255_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_ind_V_1_reg_251 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln259_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_i_col_046_0_phi_fu_266_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_col_V_0_reg_274 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln878_14_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal row_ind_V_0_reg_306 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_2_reg_285 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_1_2_reg_295 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_V_reg_318 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_col_V_phi_fu_334_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_Val2_s_phi_fu_358_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_366 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_366 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_366 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_366 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_buf_cop_V_0_0_phi_fu_382_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_V_0_fu_673_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_Val2_4_phi_fu_393_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_Val2_3_phi_fu_416_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln534_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln534_4_fu_557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln534_6_fu_646_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln534_5_fu_653_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1616_fu_660_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal row_ind_V_0_0_fu_92 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln301_fu_503_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_1_0_fu_96 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_2_0_fu_100 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp3_stage0_01001 : BOOLEAN;
    signal zext_ln878_fu_528_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln878_6_fu_548_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal img_height_cast_fu_562_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_576_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln878_8_fu_596_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln878_7_fu_592_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln878_10_fu_632_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln878_9_fu_628_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln886_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_10_fu_702_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln886_1_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln886_2_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_12_fu_729_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln886_3_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_13_fu_742_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln886_4_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_14_fu_756_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln886_5_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln886_6_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_V_16_fu_783_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln886_7_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp3 : STD_LOGIC;
    signal ap_enable_pp3 : STD_LOGIC;
    signal ap_condition_414 : BOOLEAN;
    signal ap_condition_209 : BOOLEAN;
    signal ap_condition_77 : BOOLEAN;
    signal ap_condition_226 : BOOLEAN;
    signal ap_condition_774 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component colordetect_accel_xfExtractPixels_1_1_0_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component colordetect_accel_mux_32_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component colordetect_accel_xferode_2160_3840_1_0_1_0_3841_3_3_s_buf_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buf_V_0_U : component colordetect_accel_xferode_2160_3840_1_0_1_0_3841_3_3_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_0_address0,
        ce0 => buf_V_0_ce0,
        q0 => buf_V_0_q0,
        address1 => buf_V_0_address1,
        ce1 => buf_V_0_ce1,
        we1 => buf_V_0_we1,
        d1 => buf_V_0_d1);

    buf_V_1_U : component colordetect_accel_xferode_2160_3840_1_0_1_0_3841_3_3_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_1_address0,
        ce0 => buf_V_1_ce0,
        q0 => buf_V_1_q0,
        address1 => buf_V_1_address1,
        ce1 => buf_V_1_ce1,
        we1 => buf_V_1_we1,
        d1 => buf_V_1_d1);

    buf_V_2_U : component colordetect_accel_xferode_2160_3840_1_0_1_0_3841_3_3_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_2_address0,
        ce0 => buf_V_2_ce0,
        q0 => buf_V_2_q0,
        address1 => buf_V_2_address1,
        ce1 => buf_V_2_ce1,
        we1 => buf_V_2_we1,
        d1 => buf_V_2_d1);

    src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460 : component colordetect_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_ready,
        p_read1 => ap_phi_mux_buf_cop_V_0_0_phi_fu_382_p4,
        ap_return => src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_return);

    src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466 : component colordetect_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_ready,
        p_read1 => ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_437,
        ap_return => src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_return);

    src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472 : component colordetect_accel_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472_ap_ready,
        p_read1 => ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_448,
        ap_return => src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472_ap_return);

    mux_32_8_1_1_U123 : component colordetect_accel_mux_32_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_0_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => trunc_ln136_reg_911,
        dout => buf_cop_V_0_fu_673_p5);

    mux_32_8_1_1_U124 : component colordetect_accel_mux_32_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_0_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => trunc_ln136_1_reg_916,
        dout => tmp_fu_685_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state4))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state4))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp3_flush_enable)) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
                elsif ((((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp3_exit_iter4_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp3_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp3_exit_iter4_state14))) then 
                    ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter3;
                elsif ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp3_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_366_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if ((ap_const_boolean_1 = ap_condition_414)) then 
                    ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_366 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_366 <= ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_366;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_378_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if (((icmp_ln878_18_fu_641_p2 = ap_const_lv1_0) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_378 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_378 <= ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_378;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_437_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if (((icmp_ln878_18_fu_641_p2 = ap_const_lv1_0) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_437 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_437 <= ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_437;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if (((icmp_ln878_18_fu_641_p2 = ap_const_lv1_0) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_448 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_448 <= ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_448;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_366_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_226)) then
                if ((ap_const_boolean_1 = ap_condition_77)) then 
                    ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_366 <= imgHelper2_4102_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_366 <= ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_366;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_437_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter3 = ap_const_logic_1))) then
                if (((icmp_ln878_18_reg_930_pp3_iter2_reg = ap_const_lv1_1) and (icmp_ln878_17_reg_926_pp3_iter2_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_437 <= tmp_fu_685_p5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_437 <= ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_437;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter3 = ap_const_logic_1))) then
                if (((icmp_ln878_18_reg_930_pp3_iter2_reg = ap_const_lv1_1) and (icmp_ln878_17_reg_926_pp3_iter2_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_448 <= ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_366;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_448 <= ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_448;
                end if;
            end if; 
        end if;
    end process;

    col_V_reg_330_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
                col_V_reg_330 <= col_V_2_reg_921;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                col_V_reg_330 <= ap_const_lv13_0;
            end if; 
        end if;
    end process;

    i_col_046_0_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_col_046_0_reg_262 <= ap_const_lv13_0;
            elsif (((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                i_col_046_0_reg_262 <= add_ln691_reg_868;
            end if; 
        end if;
    end process;

    i_col_V_0_reg_274_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_col_V_0_reg_274 <= ap_const_lv13_0;
            elsif (((icmp_ln878_14_fu_552_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                i_col_V_0_reg_274 <= add_ln691_4_fu_542_p2;
            end if; 
        end if;
    end process;

    p_Val2_3_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
                p_Val2_3_reg_412 <= src_buf_V_1_0_reg_400;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                p_Val2_3_reg_412 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    p_Val2_4_reg_389_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
                p_Val2_4_reg_389 <= src_buf_V_2_0_reg_424;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                p_Val2_4_reg_389 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then 
                p_Val2_s_reg_354 <= src_buf_V_0_0_reg_342;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                p_Val2_s_reg_354 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    row_V_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln878_15_fu_586_p2 = ap_const_lv1_0))) then 
                row_V_reg_318 <= ap_const_lv13_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                row_V_reg_318 <= row_V_2_fu_803_p2;
            end if; 
        end if;
    end process;

    row_ind_V_0_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln878_15_fu_586_p2 = ap_const_lv1_0))) then 
                row_ind_V_0_reg_306 <= row_ind_V_0_0_load_reg_850;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                row_ind_V_0_reg_306 <= row_ind_V_1_2_reg_295;
            end if; 
        end if;
    end process;

    row_ind_V_1_2_reg_295_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln878_15_fu_586_p2 = ap_const_lv1_0))) then 
                row_ind_V_1_2_reg_295 <= row_ind_V_1_0_load_reg_855;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                row_ind_V_1_2_reg_295 <= row_ind_V_2_reg_285;
            end if; 
        end if;
    end process;

    row_ind_V_1_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln259_fu_497_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                row_ind_V_1_reg_251 <= init_row_ind_fu_482_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                row_ind_V_1_reg_251 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    row_ind_V_2_reg_285_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln878_15_fu_586_p2 = ap_const_lv1_0))) then 
                row_ind_V_2_reg_285 <= row_ind_V_2_0_load_reg_860;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                row_ind_V_2_reg_285 <= row_ind_V_0_reg_306;
            end if; 
        end if;
    end process;

    src_buf_V_0_0_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then 
                src_buf_V_0_0_reg_342 <= src_buf_V_0_1_reg_963;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                src_buf_V_0_0_reg_342 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_V_1_0_reg_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
                src_buf_V_1_0_reg_400 <= src_buf_V_1_1_reg_974;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                src_buf_V_1_0_reg_400 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_V_2_0_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
                src_buf_V_2_0_reg_424 <= src_buf_V_2_1_reg_979;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then 
                src_buf_V_2_0_reg_424 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln1616_reg_890 <= add_ln1616_fu_571_p2;
                icmp_ln878_15_reg_895 <= icmp_ln878_15_fu_586_p2;
                op2_assign_reg_885 <= op2_assign_fu_565_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                add_ln691_reg_868 <= add_ln691_fu_522_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_378 <= ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_378;
                ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_437 <= ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_437;
                ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_448 <= ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_448;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_366 <= ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_366;
                ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_378 <= ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_378;
                ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_437 <= ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_437;
                ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_448 <= ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_448;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln878_16_fu_600_p2 = ap_const_lv1_1) and (icmp_ln878_15_reg_895 = ap_const_lv1_0))) then
                cmp_i_i115_i_reg_903 <= cmp_i_i115_i_fu_605_p2;
                trunc_ln123_reg_907 <= trunc_ln123_fu_610_p1;
                trunc_ln136_1_reg_916 <= trunc_ln136_1_fu_618_p1;
                trunc_ln136_reg_911 <= trunc_ln136_fu_614_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                col_V_2_reg_921 <= col_V_2_fu_622_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                col_V_reg_330_pp3_iter1_reg <= col_V_reg_330;
                icmp_ln878_17_reg_926 <= icmp_ln878_17_fu_636_p2;
                icmp_ln878_17_reg_926_pp3_iter1_reg <= icmp_ln878_17_reg_926;
                icmp_ln878_18_reg_930_pp3_iter1_reg <= icmp_ln878_18_reg_930;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_reg_840 <= empty_fu_478_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp3_stage0_11001)) then
                icmp_ln878_17_reg_926_pp3_iter2_reg <= icmp_ln878_17_reg_926_pp3_iter1_reg;
                icmp_ln878_17_reg_926_pp3_iter3_reg <= icmp_ln878_17_reg_926_pp3_iter2_reg;
                icmp_ln878_17_reg_926_pp3_iter4_reg <= icmp_ln878_17_reg_926_pp3_iter3_reg;
                icmp_ln878_18_reg_930_pp3_iter2_reg <= icmp_ln878_18_reg_930_pp3_iter1_reg;
                icmp_ln882_reg_954_pp3_iter3_reg <= icmp_ln882_reg_954;
                icmp_ln882_reg_954_pp3_iter4_reg <= icmp_ln882_reg_954_pp3_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                icmp_ln878_18_reg_930 <= icmp_ln878_18_fu_641_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln878_reg_873 <= icmp_ln878_fu_532_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter1_reg = ap_const_lv1_1))) then
                icmp_ln882_reg_954 <= icmp_ln882_fu_667_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter2_reg = ap_const_lv1_1))) then
                max_V_11_reg_968 <= max_V_11_fu_716_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then
                max_V_15_reg_986 <= max_V_15_fu_770_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln259_fu_497_p2 = ap_const_lv1_0) and (ap_phi_mux_row_ind_V_1_phi_fu_255_p4 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_V_0_0_fu_92(1 downto 0) <= zext_ln301_fu_503_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    row_ind_V_0_0_load_reg_850(1 downto 0) <= row_ind_V_0_0_fu_92(1 downto 0);
                    row_ind_V_1_0_load_reg_855(1 downto 0) <= row_ind_V_1_0_fu_96(1 downto 0);
                    row_ind_V_2_0_load_reg_860(1 downto 0) <= row_ind_V_2_0_fu_100(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln259_fu_497_p2 = ap_const_lv1_0) and (ap_phi_mux_row_ind_V_1_phi_fu_255_p4 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_V_1_0_fu_96(1 downto 0) <= zext_ln301_fu_503_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_phi_mux_row_ind_V_1_phi_fu_255_p4 = ap_const_lv2_1)) and not((ap_phi_mux_row_ind_V_1_phi_fu_255_p4 = ap_const_lv2_0)) and (icmp_ln259_fu_497_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_V_2_0_fu_100(1 downto 0) <= zext_ln301_fu_503_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter3 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter2_reg = ap_const_lv1_1))) then
                src_buf_V_0_1_reg_963 <= src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then
                src_buf_V_1_1_reg_974 <= src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_return;
                src_buf_V_2_1_reg_979 <= src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_472_ap_return;
            end if;
        end if;
    end process;
    row_ind_V_0_0_load_reg_850(12 downto 2) <= "00000000000";
    row_ind_V_1_0_load_reg_855(12 downto 2) <= "00000000000";
    row_ind_V_2_0_load_reg_860(12 downto 2) <= "00000000000";
    row_ind_V_0_0_fu_92(12 downto 2) <= "00000000000";
    row_ind_V_1_0_fu_96(12 downto 2) <= "00000000000";
    row_ind_V_2_0_fu_100(12 downto 2) <= "00000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, icmp_ln878_fu_532_p2, ap_CS_fsm_state7, icmp_ln878_15_reg_895, icmp_ln878_16_fu_600_p2, ap_CS_fsm_state9, ap_enable_reg_pp3_iter3, ap_enable_reg_pp3_iter4, ap_block_pp1_stage0_subdone, ap_block_pp3_stage0_subdone, icmp_ln259_fu_497_p2, icmp_ln878_14_fu_552_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln259_fu_497_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln878_fu_532_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln878_fu_532_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln878_14_fu_552_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and ((icmp_ln878_16_fu_600_p2 = ap_const_lv1_0) or (icmp_ln878_15_reg_895 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                end if;
            when ap_ST_fsm_pp3_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln1616_fu_571_p2 <= std_logic_vector(unsigned(empty_reg_840) + unsigned(ap_const_lv14_1));
    add_ln691_4_fu_542_p2 <= std_logic_vector(unsigned(i_col_V_0_reg_274) + unsigned(ap_const_lv13_1));
    add_ln691_fu_522_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_col_046_0_phi_fu_266_p4) + unsigned(ap_const_lv13_1));
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp3_stage0 <= ap_CS_fsm(8);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state16 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(7);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_11001_assign_proc : process(imgHelper2_4102_empty_n, ap_enable_reg_pp1_iter1, icmp_ln878_reg_873)
    begin
                ap_block_pp1_stage0_11001 <= ((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (imgHelper2_4102_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(imgHelper2_4102_empty_n, ap_enable_reg_pp1_iter1, icmp_ln878_reg_873)
    begin
                ap_block_pp1_stage0_subdone <= ((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (imgHelper2_4102_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp3_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp3_stage0_01001_assign_proc : process(imgHelper2_4102_empty_n, imgHelper3_4103_full_n, ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter5, icmp_ln882_reg_954_pp3_iter4_reg, ap_predicate_op126_read_state11)
    begin
                ap_block_pp3_stage0_01001 <= (((ap_predicate_op126_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (imgHelper2_4102_empty_n = ap_const_logic_0)) or ((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (imgHelper3_4103_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp3_stage0_11001_assign_proc : process(imgHelper2_4102_empty_n, imgHelper3_4103_full_n, ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter5, icmp_ln882_reg_954_pp3_iter4_reg, ap_predicate_op126_read_state11)
    begin
                ap_block_pp3_stage0_11001 <= (((ap_predicate_op126_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (imgHelper2_4102_empty_n = ap_const_logic_0)) or ((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (imgHelper3_4103_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp3_stage0_subdone_assign_proc : process(imgHelper2_4102_empty_n, imgHelper3_4103_full_n, ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter5, icmp_ln882_reg_954_pp3_iter4_reg, ap_predicate_op126_read_state11)
    begin
                ap_block_pp3_stage0_subdone <= (((ap_predicate_op126_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (imgHelper2_4102_empty_n = ap_const_logic_0)) or ((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (imgHelper3_4103_full_n = ap_const_logic_0)));
    end process;

        ap_block_state10_pp3_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp3_stage0_iter1_assign_proc : process(imgHelper2_4102_empty_n, ap_predicate_op126_read_state11)
    begin
                ap_block_state11_pp3_stage0_iter1 <= ((ap_predicate_op126_read_state11 = ap_const_boolean_1) and (imgHelper2_4102_empty_n = ap_const_logic_0));
    end process;

        ap_block_state12_pp3_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp3_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp3_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state15_pp3_stage0_iter5_assign_proc : process(imgHelper3_4103_full_n, icmp_ln882_reg_954_pp3_iter4_reg)
    begin
                ap_block_state15_pp3_stage0_iter5 <= ((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (imgHelper3_4103_full_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp1_stage0_iter1_assign_proc : process(imgHelper2_4102_empty_n, icmp_ln878_reg_873)
    begin
                ap_block_state5_pp1_stage0_iter1 <= ((icmp_ln878_reg_873 = ap_const_lv1_1) and (imgHelper2_4102_empty_n = ap_const_logic_0));
    end process;


    ap_condition_209_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_block_pp3_stage0_11001, ap_enable_reg_pp3_iter0)
    begin
                ap_condition_209 <= ((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0));
    end process;


    ap_condition_226_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0_11001)
    begin
                ap_condition_226 <= ((ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0));
    end process;


    ap_condition_414_assign_proc : process(cmp_i_i115_i_reg_903, icmp_ln878_17_fu_636_p2, icmp_ln878_18_fu_641_p2)
    begin
                ap_condition_414 <= ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_fu_641_p2 = ap_const_lv1_1) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_1));
    end process;


    ap_condition_77_assign_proc : process(icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903)
    begin
                ap_condition_77 <= ((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1));
    end process;


    ap_condition_774_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, trunc_ln123_reg_907)
    begin
                ap_condition_774 <= (not((trunc_ln123_reg_907 = ap_const_lv2_0)) and not((trunc_ln123_reg_907 = ap_const_lv2_1)) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0));
    end process;


    ap_condition_pp1_exit_iter0_state4_assign_proc : process(icmp_ln878_fu_532_p2)
    begin
        if ((icmp_ln878_fu_532_p2 = ap_const_lv1_0)) then 
            ap_condition_pp1_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp3_exit_iter4_state14_assign_proc : process(ap_enable_reg_pp3_iter3, ap_enable_reg_pp3_iter4)
    begin
        if (((ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0))) then 
            ap_condition_pp3_exit_iter4_state14 <= ap_const_logic_1;
        else 
            ap_condition_pp3_exit_iter4_state14 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp3_flush_enable_assign_proc : process(ap_CS_fsm_pp3_stage0, icmp_ln878_17_fu_636_p2, ap_block_pp3_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (icmp_ln878_17_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            ap_condition_pp3_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp3_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln878_15_reg_895, icmp_ln878_16_fu_600_p2, ap_CS_fsm_state9)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and ((icmp_ln878_16_fu_600_p2 = ap_const_lv1_0) or (icmp_ln878_15_reg_895 = ap_const_lv1_1))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp3 <= (ap_idle_pp3 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp3_assign_proc : process(ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter5, ap_enable_reg_pp3_iter0, ap_enable_reg_pp3_iter3, ap_enable_reg_pp3_iter4, ap_enable_reg_pp3_iter2)
    begin
        if (((ap_enable_reg_pp3_iter5 = ap_const_logic_0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0) and (ap_enable_reg_pp3_iter2 = ap_const_logic_0) and (ap_enable_reg_pp3_iter4 = ap_const_logic_0) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0))) then 
            ap_idle_pp3 <= ap_const_logic_1;
        else 
            ap_idle_pp3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_buf_cop_V_0_0_phi_fu_382_p4_assign_proc : process(icmp_ln878_17_reg_926_pp3_iter2_reg, icmp_ln878_18_reg_930_pp3_iter2_reg, buf_cop_V_0_fu_673_p5, ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_378)
    begin
        if (((icmp_ln878_18_reg_930_pp3_iter2_reg = ap_const_lv1_1) and (icmp_ln878_17_reg_926_pp3_iter2_reg = ap_const_lv1_1))) then 
            ap_phi_mux_buf_cop_V_0_0_phi_fu_382_p4 <= buf_cop_V_0_fu_673_p5;
        else 
            ap_phi_mux_buf_cop_V_0_0_phi_fu_382_p4 <= ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_378;
        end if; 
    end process;


    ap_phi_mux_col_V_phi_fu_334_p4_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, col_V_reg_330, col_V_2_reg_921)
    begin
        if (((icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            ap_phi_mux_col_V_phi_fu_334_p4 <= col_V_2_reg_921;
        else 
            ap_phi_mux_col_V_phi_fu_334_p4 <= col_V_reg_330;
        end if; 
    end process;


    ap_phi_mux_i_col_046_0_phi_fu_266_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_reg_873, i_col_046_0_reg_262, add_ln691_reg_868)
    begin
        if (((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_i_col_046_0_phi_fu_266_p4 <= add_ln691_reg_868;
        else 
            ap_phi_mux_i_col_046_0_phi_fu_266_p4 <= i_col_046_0_reg_262;
        end if; 
    end process;


    ap_phi_mux_p_Val2_3_phi_fu_416_p4_assign_proc : process(ap_block_pp3_stage0, ap_enable_reg_pp3_iter5, src_buf_V_1_0_reg_400, p_Val2_3_reg_412, icmp_ln878_17_reg_926_pp3_iter4_reg)
    begin
        if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
            ap_phi_mux_p_Val2_3_phi_fu_416_p4 <= src_buf_V_1_0_reg_400;
        else 
            ap_phi_mux_p_Val2_3_phi_fu_416_p4 <= p_Val2_3_reg_412;
        end if; 
    end process;


    ap_phi_mux_p_Val2_4_phi_fu_393_p4_assign_proc : process(ap_block_pp3_stage0, ap_enable_reg_pp3_iter5, p_Val2_4_reg_389, src_buf_V_2_0_reg_424, icmp_ln878_17_reg_926_pp3_iter4_reg)
    begin
        if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
            ap_phi_mux_p_Val2_4_phi_fu_393_p4 <= src_buf_V_2_0_reg_424;
        else 
            ap_phi_mux_p_Val2_4_phi_fu_393_p4 <= p_Val2_4_reg_389;
        end if; 
    end process;


    ap_phi_mux_p_Val2_s_phi_fu_358_p4_assign_proc : process(ap_block_pp3_stage0, src_buf_V_0_0_reg_342, p_Val2_s_reg_354, icmp_ln878_17_reg_926_pp3_iter3_reg, ap_enable_reg_pp3_iter4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then 
            ap_phi_mux_p_Val2_s_phi_fu_358_p4 <= src_buf_V_0_0_reg_342;
        else 
            ap_phi_mux_p_Val2_s_phi_fu_358_p4 <= p_Val2_s_reg_354;
        end if; 
    end process;

    ap_phi_mux_row_ind_V_1_phi_fu_255_p4 <= row_ind_V_1_reg_251;

    ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4_assign_proc : process(ap_block_pp3_stage0, src_buf_V_0_0_reg_342, icmp_ln878_17_reg_926_pp3_iter3_reg, src_buf_V_0_1_reg_963, ap_enable_reg_pp3_iter4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1) and (icmp_ln878_17_reg_926_pp3_iter3_reg = ap_const_lv1_1))) then 
            ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4 <= src_buf_V_0_1_reg_963;
        else 
            ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4 <= src_buf_V_0_0_reg_342;
        end if; 
    end process;


    ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4_assign_proc : process(ap_block_pp3_stage0, ap_enable_reg_pp3_iter5, src_buf_V_1_0_reg_400, icmp_ln878_17_reg_926_pp3_iter4_reg, src_buf_V_1_1_reg_974)
    begin
        if (((ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (icmp_ln878_17_reg_926_pp3_iter4_reg = ap_const_lv1_1))) then 
            ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4 <= src_buf_V_1_1_reg_974;
        else 
            ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4 <= src_buf_V_1_0_reg_400;
        end if; 
    end process;

    ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_366 <= "XXXXXXXX";
    ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_378 <= "XXXXXXXX";
    ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_437 <= "XXXXXXXX";
    ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_448 <= "XXXXXXXX";

    ap_predicate_op126_read_state11_assign_proc : process(icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903)
    begin
                ap_predicate_op126_read_state11 <= ((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(icmp_ln878_15_reg_895, icmp_ln878_16_fu_600_p2, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and ((icmp_ln878_16_fu_600_p2 = ap_const_lv1_0) or (icmp_ln878_15_reg_895 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_0_address0 <= zext_ln1616_fu_660_p1(12 - 1 downto 0);

    buf_V_0_address1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_CS_fsm_state7, trunc_ln123_reg_907, zext_ln534_4_fu_557_p1, zext_ln534_6_fu_646_p1, zext_ln534_5_fu_653_p1)
    begin
        if (((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0))) then 
            buf_V_0_address1 <= zext_ln534_5_fu_653_p1(12 - 1 downto 0);
        elsif (((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0))) then 
            buf_V_0_address1 <= zext_ln534_6_fu_646_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_V_0_address1 <= zext_ln534_4_fu_557_p1(12 - 1 downto 0);
        else 
            buf_V_0_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_0_ce0_assign_proc : process(ap_block_pp3_stage0_11001, ap_enable_reg_pp3_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter2 = ap_const_logic_1))) then 
            buf_V_0_ce0 <= ap_const_logic_1;
        else 
            buf_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_0_ce1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, ap_CS_fsm_state7, trunc_ln123_reg_907)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0)) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0)))) then 
            buf_V_0_ce1 <= ap_const_logic_1;
        else 
            buf_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_0_d1_assign_proc : process(imgHelper2_4102_dout, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_CS_fsm_state7, trunc_ln123_reg_907)
    begin
        if (((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0))) then 
            buf_V_0_d1 <= imgHelper2_4102_dout;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0)))) then 
            buf_V_0_d1 <= ap_const_lv8_0;
        else 
            buf_V_0_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_0_we1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, ap_CS_fsm_state7, trunc_ln123_reg_907, icmp_ln878_14_fu_552_p2)
    begin
        if ((((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0)) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_0)) or ((icmp_ln878_14_fu_552_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            buf_V_0_we1 <= ap_const_logic_1;
        else 
            buf_V_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_1_address0 <= zext_ln1616_fu_660_p1(12 - 1 downto 0);

    buf_V_1_address1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, trunc_ln123_reg_907, zext_ln534_fu_537_p1, zext_ln534_6_fu_646_p1, zext_ln534_5_fu_653_p1)
    begin
        if (((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1))) then 
            buf_V_1_address1 <= zext_ln534_5_fu_653_p1(12 - 1 downto 0);
        elsif (((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1))) then 
            buf_V_1_address1 <= zext_ln534_6_fu_646_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            buf_V_1_address1 <= zext_ln534_fu_537_p1(12 - 1 downto 0);
        else 
            buf_V_1_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_1_ce0_assign_proc : process(ap_block_pp3_stage0_11001, ap_enable_reg_pp3_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter2 = ap_const_logic_1))) then 
            buf_V_1_ce0 <= ap_const_logic_1;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, ap_block_pp1_stage0_11001, trunc_ln123_reg_907)
    begin
        if ((((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1)) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            buf_V_1_ce1 <= ap_const_logic_1;
        else 
            buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_d1_assign_proc : process(imgHelper2_4102_dout, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, trunc_ln123_reg_907)
    begin
        if (((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1))) then 
            buf_V_1_d1 <= ap_const_lv8_0;
        elsif ((((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            buf_V_1_d1 <= imgHelper2_4102_dout;
        else 
            buf_V_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_we1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_reg_873, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, ap_block_pp1_stage0_11001, trunc_ln123_reg_907)
    begin
        if ((((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1)) or ((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (trunc_ln123_reg_907 = ap_const_lv2_1)))) then 
            buf_V_1_we1 <= ap_const_logic_1;
        else 
            buf_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_address0 <= zext_ln1616_fu_660_p1(12 - 1 downto 0);

    buf_V_2_address1_assign_proc : process(cmp_i_i115_i_reg_903, zext_ln534_6_fu_646_p1, zext_ln534_5_fu_653_p1, ap_condition_774)
    begin
        if ((ap_const_boolean_1 = ap_condition_774)) then
            if ((cmp_i_i115_i_reg_903 = ap_const_lv1_1)) then 
                buf_V_2_address1 <= zext_ln534_5_fu_653_p1(12 - 1 downto 0);
            elsif ((cmp_i_i115_i_reg_903 = ap_const_lv1_0)) then 
                buf_V_2_address1 <= zext_ln534_6_fu_646_p1(12 - 1 downto 0);
            else 
                buf_V_2_address1 <= "XXXXXXXXXXXX";
            end if;
        else 
            buf_V_2_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_2_ce0_assign_proc : process(ap_block_pp3_stage0_11001, ap_enable_reg_pp3_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter2 = ap_const_logic_1))) then 
            buf_V_2_ce0 <= ap_const_logic_1;
        else 
            buf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_ce1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, trunc_ln123_reg_907)
    begin
        if (((not((trunc_ln123_reg_907 = ap_const_lv2_0)) and not((trunc_ln123_reg_907 = ap_const_lv2_1)) and (cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or (not((trunc_ln123_reg_907 = ap_const_lv2_0)) and not((trunc_ln123_reg_907 = ap_const_lv2_1)) and (cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)))) then 
            buf_V_2_ce1 <= ap_const_logic_1;
        else 
            buf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_d1_assign_proc : process(imgHelper2_4102_dout, cmp_i_i115_i_reg_903, ap_condition_774)
    begin
        if ((ap_const_boolean_1 = ap_condition_774)) then
            if ((cmp_i_i115_i_reg_903 = ap_const_lv1_1)) then 
                buf_V_2_d1 <= imgHelper2_4102_dout;
            elsif ((cmp_i_i115_i_reg_903 = ap_const_lv1_0)) then 
                buf_V_2_d1 <= ap_const_lv8_0;
            else 
                buf_V_2_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_2_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_2_we1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903, ap_block_pp3_stage0_11001, trunc_ln123_reg_907)
    begin
        if (((not((trunc_ln123_reg_907 = ap_const_lv2_0)) and not((trunc_ln123_reg_907 = ap_const_lv2_1)) and (cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or (not((trunc_ln123_reg_907 = ap_const_lv2_0)) and not((trunc_ln123_reg_907 = ap_const_lv2_1)) and (cmp_i_i115_i_reg_903 = ap_const_lv1_0) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)))) then 
            buf_V_2_we1 <= ap_const_logic_1;
        else 
            buf_V_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i115_i_fu_605_p2 <= "1" when (unsigned(zext_ln878_7_fu_592_p1) < unsigned(img_height)) else "0";
    col_V_2_fu_622_p2 <= std_logic_vector(unsigned(ap_phi_mux_col_V_phi_fu_334_p4) + unsigned(ap_const_lv13_1));
    empty_fu_478_p1 <= img_width(14 - 1 downto 0);
    icmp_ln259_fu_497_p2 <= "1" when (row_ind_V_1_reg_251 = ap_const_lv2_3) else "0";
    icmp_ln878_14_fu_552_p2 <= "1" when (unsigned(zext_ln878_6_fu_548_p1) < unsigned(img_width)) else "0";
    icmp_ln878_15_fu_586_p2 <= "1" when (tmp_2_fu_576_p4 = ap_const_lv16_0) else "0";
    icmp_ln878_16_fu_600_p2 <= "1" when (unsigned(zext_ln878_8_fu_596_p1) < unsigned(op2_assign_reg_885)) else "0";
    icmp_ln878_17_fu_636_p2 <= "1" when (unsigned(zext_ln878_10_fu_632_p1) < unsigned(add_ln1616_reg_890)) else "0";
    icmp_ln878_18_fu_641_p2 <= "1" when (unsigned(zext_ln878_9_fu_628_p1) < unsigned(img_width)) else "0";
    icmp_ln878_fu_532_p2 <= "1" when (unsigned(zext_ln878_fu_528_p1) < unsigned(img_width)) else "0";
    icmp_ln882_fu_667_p2 <= "1" when (col_V_reg_330_pp3_iter1_reg = ap_const_lv13_0) else "0";
    icmp_ln886_1_fu_710_p2 <= "1" when (unsigned(src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_return) > unsigned(max_V_10_fu_702_p3)) else "0";
    icmp_ln886_2_fu_724_p2 <= "1" when (unsigned(ap_phi_mux_p_Val2_3_phi_fu_416_p4) > unsigned(max_V_11_reg_968)) else "0";
    icmp_ln886_3_fu_736_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4) > unsigned(max_V_12_fu_729_p3)) else "0";
    icmp_ln886_4_fu_750_p2 <= "1" when (unsigned(src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_return) > unsigned(max_V_13_fu_742_p3)) else "0";
    icmp_ln886_5_fu_764_p2 <= "1" when (unsigned(ap_phi_mux_p_Val2_4_phi_fu_393_p4) > unsigned(max_V_14_fu_756_p3)) else "0";
    icmp_ln886_6_fu_778_p2 <= "1" when (unsigned(src_buf_V_2_0_reg_424) > unsigned(max_V_15_reg_986)) else "0";
    icmp_ln886_7_fu_790_p2 <= "1" when (unsigned(src_buf_V_2_1_reg_979) > unsigned(max_V_16_fu_783_p3)) else "0";
    icmp_ln886_fu_696_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4) > unsigned(ap_phi_mux_p_Val2_s_phi_fu_358_p4)) else "0";

    imgHelper2_4102_blk_n_assign_proc : process(imgHelper2_4102_empty_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_reg_873, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln878_17_reg_926, icmp_ln878_18_reg_930, cmp_i_i115_i_reg_903)
    begin
        if ((((cmp_i_i115_i_reg_903 = ap_const_lv1_1) and (icmp_ln878_18_reg_930 = ap_const_lv1_1) and (icmp_ln878_17_reg_926 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or ((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            imgHelper2_4102_blk_n <= imgHelper2_4102_empty_n;
        else 
            imgHelper2_4102_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    imgHelper2_4102_read_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_reg_873, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_predicate_op126_read_state11, ap_block_pp3_stage0_11001, ap_block_pp1_stage0_11001)
    begin
        if ((((ap_predicate_op126_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or ((icmp_ln878_reg_873 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            imgHelper2_4102_read <= ap_const_logic_1;
        else 
            imgHelper2_4102_read <= ap_const_logic_0;
        end if; 
    end process;


    imgHelper3_4103_blk_n_assign_proc : process(imgHelper3_4103_full_n, ap_block_pp3_stage0, ap_enable_reg_pp3_iter5, icmp_ln882_reg_954_pp3_iter4_reg)
    begin
        if (((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0))) then 
            imgHelper3_4103_blk_n <= imgHelper3_4103_full_n;
        else 
            imgHelper3_4103_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgHelper3_4103_din <= 
        src_buf_V_2_1_reg_979 when (icmp_ln886_7_fu_790_p2(0) = '1') else 
        max_V_16_fu_783_p3;

    imgHelper3_4103_write_assign_proc : process(ap_enable_reg_pp3_iter5, icmp_ln882_reg_954_pp3_iter4_reg, ap_block_pp3_stage0_11001)
    begin
        if (((icmp_ln882_reg_954_pp3_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then 
            imgHelper3_4103_write <= ap_const_logic_1;
        else 
            imgHelper3_4103_write <= ap_const_logic_0;
        end if; 
    end process;

    img_height_cast_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(img_height),17));
    init_row_ind_fu_482_p2 <= std_logic_vector(unsigned(row_ind_V_1_reg_251) + unsigned(ap_const_lv2_1));
    max_V_10_fu_702_p3 <= 
        ap_phi_mux_src_buf_V_0_0_phi_fu_346_p4 when (icmp_ln886_fu_696_p2(0) = '1') else 
        ap_phi_mux_p_Val2_s_phi_fu_358_p4;
    max_V_11_fu_716_p3 <= 
        src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_460_ap_return when (icmp_ln886_1_fu_710_p2(0) = '1') else 
        max_V_10_fu_702_p3;
    max_V_12_fu_729_p3 <= 
        ap_phi_mux_p_Val2_3_phi_fu_416_p4 when (icmp_ln886_2_fu_724_p2(0) = '1') else 
        max_V_11_reg_968;
    max_V_13_fu_742_p3 <= 
        ap_phi_mux_src_buf_V_1_0_phi_fu_404_p4 when (icmp_ln886_3_fu_736_p2(0) = '1') else 
        max_V_12_fu_729_p3;
    max_V_14_fu_756_p3 <= 
        src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_466_ap_return when (icmp_ln886_4_fu_750_p2(0) = '1') else 
        max_V_13_fu_742_p3;
    max_V_15_fu_770_p3 <= 
        ap_phi_mux_p_Val2_4_phi_fu_393_p4 when (icmp_ln886_5_fu_764_p2(0) = '1') else 
        max_V_14_fu_756_p3;
    max_V_16_fu_783_p3 <= 
        src_buf_V_2_0_reg_424 when (icmp_ln886_6_fu_778_p2(0) = '1') else 
        max_V_15_reg_986;
    op2_assign_fu_565_p2 <= std_logic_vector(unsigned(img_height_cast_fu_562_p1) + unsigned(ap_const_lv17_1));
    row_V_2_fu_803_p2 <= std_logic_vector(unsigned(row_V_reg_318) + unsigned(ap_const_lv13_1));
    tmp_2_fu_576_p4 <= op2_assign_fu_565_p2(16 downto 1);
    trunc_ln123_fu_610_p1 <= row_ind_V_2_reg_285(2 - 1 downto 0);
    trunc_ln136_1_fu_618_p1 <= row_ind_V_1_2_reg_295(2 - 1 downto 0);
    trunc_ln136_fu_614_p1 <= row_ind_V_0_reg_306(2 - 1 downto 0);
    zext_ln1616_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_330_pp3_iter1_reg),64));
    zext_ln301_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_ind_V_1_reg_251),13));
    zext_ln534_4_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_col_V_0_reg_274),64));
    zext_ln534_5_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_330),64));
    zext_ln534_6_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_330),64));
    zext_ln534_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_col_046_0_reg_262),64));
    zext_ln878_10_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_col_V_phi_fu_334_p4),14));
    zext_ln878_6_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_col_V_0_reg_274),16));
    zext_ln878_7_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_V_reg_318),16));
    zext_ln878_8_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_V_reg_318),17));
    zext_ln878_9_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_col_V_phi_fu_334_p4),16));
    zext_ln878_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_i_col_046_0_phi_fu_266_p4),16));
end behav;
