# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0.xci
# IP: The module: 'resizer_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0.xci
# IP: The module: 'resizer_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ-HelloWorld/boards/Pynq-Z2/resizer/resizer/resizer.gen/sources_1/bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
